namespace HTTTQLDanSo.DataManagerment.DataModel
{
    public class PhieuThuTinReport2
    {
        public string Region_ID { get; set; }
        public string Region_Name { get; set; }
        public string HouseHold_ID { get; set; }
        public string HouseHold_Code { get; set; }
        public string HouseHold_Number { get; set; }
        public string Personal_ID { get; set; }
        public string Name { get; set; }
        public string DateOfBirth { get; set; }
        public string PlaceOfBirth { get; set; }
        public string Relation_Code { get; set; }
        public string Ethnic_Name { get; set; }
        public string Sex_ID { get; set; }
        public string Education_Code { get; set; }
        public string Education_Level { get; set; }
        public string Technical_Code { get; set; }
        public string Marital_Code { get; set; }
        public string Invalid_Code { get; set; }
        public string Residence_Code { get; set; }
        public string Contra_Date { get; set; }
        public string Contraceptive_Code { get; set; }
        public string DOB { get; set; }
        public string T0105 { get; set; }
        public string T0205 { get; set; }
        public string T0305 { get; set; }
        public string T0405 { get; set; }
        public string T0505 { get; set; }
        public string T0605 { get; set; }
        public string T0705 { get; set; }
        public string T0805 { get; set; }
        public string T0905 { get; set; }
        public string T1005 { get; set; }
        public string T1105 { get; set; }
        public string T1205 { get; set; }
        public string T0106 { get; set; }
        public string T0206 { get; set; }
        public string T0306 { get; set; }
        public string T0406 { get; set; }
        public string T0506 { get; set; }
        public string T0606 { get; set; }
        public string T0706 { get; set; }
        public string T0806 { get; set; }
        public string T0906 { get; set; }
        public string T1006 { get; set; }
        public string T1106 { get; set; }
        public string T1206 { get; set; }
        public string T0107 { get; set; }
        public string T0207 { get; set; }
        public string T0307 { get; set; }
        public string T0407 { get; set; }
        public string T0507 { get; set; }
        public string T0607 { get; set; }
        public string T0707 { get; set; }
        public string T0807 { get; set; }
        public string T0907 { get; set; }
        public string T1007 { get; set; }
        public string T1107 { get; set; }
        public string T1207 { get; set; }
        public string T0108 { get; set; }
        public string T0208 { get; set; }
        public string T0308 { get; set; }
        public string T0408 { get; set; }
        public string T0508 { get; set; }
        public string T0608 { get; set; }
        public string T0708 { get; set; }
        public string T0808 { get; set; }
        public string T0908 { get; set; }
        public string T1008 { get; set; }
        public string T1108 { get; set; }
        public string T1208 { get; set; }
        public string T0109 { get; set; }
        public string T0209 { get; set; }
        public string T0309 { get; set; }
        public string T0409 { get; set; }
        public string T0509 { get; set; }
        public string T0609 { get; set; }
        public string T0709 { get; set; }
        public string T0809 { get; set; }
        public string T0909 { get; set; }
        public string T1009 { get; set; }
        public string T1109 { get; set; }
        public string T1209 { get; set; }
    }
}